parameter_defaults:
  CinderBackupBackend: ceph
  CephPoolDefaultSize: 2
  CephConfigOverrides:
    osd_pool_default_size: 2
    osd_pool_default_min_size: 2
    osd_pool_default_pg_num: 16
    osd_pool_default_pgp_num: 16
    osd_recovery_op_priority: 2
    osd_recovery_max_active: 2
    osd_max_backfills: 1
  #NOTE: below needs to be derived using pgcalc
  CephPools:
    - name: volumes
      pg_num: 512
      application: rbd
    - name: vms
      pg_num: 128
      application: rbd
    - name: images
      pg_num: 64
      application: rbd
    - name: backups
      pg_num: 128
      application: rbd
    - name: metrics
      pg_num: 128
      application: openstack_gnocchi
    - name: default.rgw.buckets.index
      pg_num: 32
      application: rgw
    - name: default.rgw.buckets.data
      pg_num: 256
      application: rgw
  CephAnsibleDisksConfig:
    dmcrypt: false
    osd_auto_discovery: true
    osd_scenario: lvm
    osd_objectstore: bluestore
